### ISSUE TITLE
6-3 で負の数を渡した場合の出力がない

### ISSUE THREAD

**Issue by tyochiai** [mokelab/software_dev_quiz#1]
6-3 で add1() に負の数を渡して err != nil となった場合の出力がありません。
err を fmt.Printf() 等で出力するか、fmt.Errof() でラップした戻り値で更になにかするか、いずれかが意図であるように思われます。

**Comment by fkmhrk** [comment]
ご指摘ありがとうございます。
`fmt.Printf()` に直しました。。。
